const List = [
  {
    type: "Tacos",
    location: "Birria",
    image: "/product5.png",
    description:
      "(3 Tacos) Beef birria, Oaxaca cheese, onions, and cilantro. (served with consommé)",
    price: "$14.99",
    like: "73",
  },
  {
    type: "Tacos",
    location: "Carne Asada",
    image: "/product5.png",
    description: "(3 Tacos) Grilled steak, salsa verde, onions, and cilantro.",
    price: "$15.99",
    like: "40",
  },
  {
    type: "Tacos",
    location: "Caribbean Tacos",
    image: "/product5.png",
    description:
      "(3 Tacos) Marinated steak topped with sliced plantains, cotija cheese, avocado ranch, and cilantro.",
    price: "$15.99",
    like: "8",
  },
  {
    type: "Tacos",
    location: "Chicken Achiote",
    image: "/product7.png",
    description:
      "(3 Tacos) Achiote chicken thigh, pickled onions, cotija cheese, and cilantro.",
    price: "$14.99",
    like: "11",
  },
  {
    type: "Tacos",
    location: "Mahi Mahi Taco",
    image: "/product8.png",
    description:
      "(3 Tacos) Crispy battered fresh fish, shaved cabbage, spicy crema, pico de gallo, and cilantro.",
    price: "$15.99",
    like: "21",
  },
  {
    type: "Tacos",
    location: "Bang Bang Shrimp Taco",
    image: "/product5.png",
    description:
      "(3 Tacos) Fried shrimp, lettuce, spicy mayo, pickled onions, and cilantro.",
    price: "$15.99",
    like: "40",
  },
  {
    type: "Tacos",
    location: "Southwest Chicken Tacos",
    image: "/product9.png",
    description:
      "(3 Tacos) Grilled chicken topped with cotija cheese, fried onions, cilantro, spicy mayo, and a black bean…",
    price: "$15.99",
    like: "9",
  },
  {
    type: "Tacos",
    location: "Party Taco Platter",
    image: "/product10.png",
    description:
      "30 tacos. Can choose in increments of 5. Please use 'Special Instructions' section for specific order.",
    price: "$125.99",
    like: "14",
  },

  {
    type: "Entrées",
    location: "Two Toastada",
    image: "/product11.png",
    description:
      "Refried beans, tostada, achiote chicken, salsa verde, cotija cheese, and jalapeños.",
    price: "$13.99",
    like: "7",
  },
  {
    type: "Entrées",
    location: "Birria Burrito",
    image: "/product12.png",
    description:
      "Mexican rice, refried beans, cheese sauce, takis chips, guacamole & your choice of protein served with a side…",
    price: "$13.99",
    like: "21",
  },
  {
    type: "Entrées",
    location: "Rice Bowls",
    image: "/product13.png",
    description:
      "Mexican rice, refried beans, lettuce, pico de Gallo, and avocado ranch.",
    price: "$14.99",
    like: "13",
  },
  {
    type: "Entrées",
    location: "Quesa Birria",
    image: "/product14.png",
    description:
      "Birria, Oaxaca cheese, onions, and cilantro. Served with chips and consommé.",
    price: "$14.99",
    like: "25",
  },
  {
    type: "Entrées",
    location: "Loaded Nachos",
    image: "/product15.png",
    description:
      "Loaded nachos, Queso, refried beans, protein, pico degallo, sour cream, and guacamole. Topped with…",
    price: "$14.99",
    like: "24",
  },
  {
    type: "Entrées",
    location: "Birria Grilled Cheese",
    image: "/product16.png",
    description:
      "Texas toast, birria, cheese, onions, and cilantro. Served with fries and tomato basil soup.",
    price: "$12.99",
    like: "12",
  },
  {
    type: "Sides",
    location: "Street Corn in a Cup",
    image: "/product17.png",
    price: "$6.99",
    like: "34",
  },
  {
    type: "Sides",
    location: "Rice",
    image: "/product18.png",
    price: "$2.99",
    like: "8",
  },
  {
    type: "Sides",
    location: "Refried Beans",
    image: "/product19.png",
    price: "$2.99",
    like: "6",
  },
  {
    type: "Sides",
    location: "Refried Beans",
    image: "/product20.png",
    price: "$7.99",
    like: "12",
  },
  {
    type: "Sides",
    location: "Guacamole",
    image: "/product21.png",
    price: "$5.99",
    like: "3",
  },
  {
    type: "Sides",
    location: "Queso and chips",
    image: "/product22.png",
    price: "$7.99",
    like: "9",
  },
  {
    type: "Sides",
    location: "Pico de Gallo",
    image: "/product23.png",
    price: "$3.99",
    like: "8",
  },
  {
    type: "Sides",
    location: "Chips",
    image: "/product24.png",
    price: "$2.99",
    like: "9",
  },
  {
    type: "Sides",
    location: "Fries",
    image: "/product5.png",
    price: "$3.99",
    like: "10",
  },
  {
    type: "Sides",
    location: "Sweet Plantains",
    image: "/product25.png",
    price: "$5.50",
    like: "12",
  },
  {
    type: "Light Menu",
    location: "Quesadilla",
    image: "/product26.png",
    description: "Quesadilla with chips",
    price: "$6.99",
    like: "7",
  },
  {
    type: "Light Menu",
    location: "Chicken Tenders and Fries",
    image: "/product27.png",
    price: "$7.50",
    like: "5",
  },
  {
    type: "Dessert",
    location: "Churros",
    image: "/product28.png",
    price: "$7.50",
    like: "21",
  },
  {
    type: "Dessert",
    location: "Takin and Chamoy Gummies",
    image: "/product29.png",
    price: "$4.50",
    like: "1",
  },
  {
    type: "Homemade Drinks",
    location: "Horchata",
    image: "/product5.png",
    price: "$4.50",
    like: "5",
  },
  {
    type: "Beverages",
    location: "Mexican Coke",
    image: "/product29.png",
    price: "$3.50",
    like: "8",
  },
  {
    type: "Beverages",
    location: "Mexican Sprite",
    image: "/product30.png",
    price: "$3.50",
    like: "5",
  },
  {
    type: "Beverages",
    image: "/product31.png",
    location: "Jarritos",
    price: "$3.50",
    like: "7",
  },
  {
    type: "Beverages",
    image: "/product5.png",
    location: "Water Bottle",
    price: "$1.50",
    like: "4",
  },
  {
    type: "Beverages",
    image: "/product5.png",
    location: "Canned Drinks",
    price: "$2.50",
    like: "1",
  },
  {
    type: "House Juices",
    image: "/product32.png",
    location: "Sweet Peach Tea",
    price: "$4.50",
    like: "",
  },
  {
    type: "House Juices",
    image: "/product33.png",
    location: "Mango",
    price: "$4.50",
    like: "",
  },
  {
    type: "House Juices",
    image: "/product33.png",
    location: "Strawberry Dragonfruit",
    price: "$5.90",
    like: "",
  },
  {
    type: "House Juices",
    image: "/product33.png",
    location: "Berry patch",
    price: "$4.50",
    like: "",
  },
];

export default List;
